#!/usr/bin/env bash
# Installs nginx and configures it to serve a page containing "Holberton School"
# when queried at the root with a GET request, on port 80.

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

service nginx start || service nginx restart

